package com.demo.centralAlarm;

import com.dppware.droolsDemo.bean.*;

dialect  "mvel"

/**
* Always exec when a central alarm is added to the environment
**/
rule "Received Sensor Active Device Event"
	when
     	$ca : CentralAlarm()
     	$de : DeviceEvent(value =="50")
    then
	    System.out.println("Received Device Event "+ $de);
	    modify($ca){
			  	setStatus("fired");
		}
    	System.out.println("On central Alarm "+$ca);
	    
end

/**
* Each device event incoming
**/
rule "Received Sensor Device Event"
	when
		$ca : CentralAlarm()
     	$de : DeviceEvent()
    then
	    System.out.println("Received Device Event "+ $de);
	    System.out.println("On central Alarm "+$ca);
	    
end



/**
* When the Alarm is Fired
**/
rule "Alarm Fired"
	timer ( int: 10s 2s )
	when
     	$ca : CentralAlarm(status == "fired")
    then
	   System.out.println("Panic!!! Panic!!!");
	   System.out.println("Panic!!! Panic!!!");
	   System.out.println("Panic!!! Panic!!!");
end