package com.demo.centralAlarm;

import com.dppware.droolsDemo.bean.*;
import com.dppware.droolsDemo.bean.device.*;
import com.dppware.droolsDemo.bean.event.*;

import java.util.Date;

dialect  "mvel"

/**
* Always exec when a Lock  is added  added to the environment
**/
rule "When Door is open send Notification "
	when
     	$ps : Lock(status == "open")
    then
    	smsService.sendSMS($ps + " Ha pasado a abierto");
end

/**
* Always after 10 seconds open the lock will be closed
**/
rule "Always after 10 seconds open the lock will be closed "
	timer ( int: 10s )
	when
     	$lock : Lock(status == "open")
    then
   		$lock.close();
   		System.out.println("ahora es "+new Date());
end


/**
* Always after 10 seconds open the lock will be closed
**/
rule "Monitoring door is closed "
	when
     	$lock : Lock(status == "closed")
    then
   		System.out.println("La puerta esta cerrada, todo va bien");
end



rule "When a Device Lock Event arrives "
	when
     	$dle : DeviceLockEvent(value == "open")
     	$lock : Lock(id == $dle.name)
     	
    then
    	modify($lock){
   			setStatus($dle.getValue());
   		}
    	System.out.println("Ha entrado evento para el lock "+$lock.id);
end



